apiVersion: v2
name: webapp-helm-chart
description: A Helm chart for Kubernetes
type: application
version: 1.2.0
appVersion: 1.16.0
home: https://github.com/csye7125-fall2023-group05/webapp-helm-chart
keywords:
  - CSYE-7125 HELM Chart
maintainers:
  - name: Siddharth Rawat
    email: rawat.sid@northeastern.edu
    url: https://sydrawat.live
  - name: Rishab Rajesh Agarwal
    email: agarwal.risha@northeastern.edu
  - name: Karan Wadhwa
    email: wadhwa.k@northeastern.edu
dependencies:
  - name: postgresql
    version: 13.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: psql.enabled
