# Default values for webapp-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  username: rishabhagarwal14628
  containerImg: quay.io/pwncorp/webapp:latest
  initContainerImg: quay.io/pwncorp/migrate:latest
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

namespace: webapp

deployStrat:
  rolling: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0

progressDeadlineSeconds: 120
minReadySeconds: 30

probes:
  path: /healthz

config:
  app_hostname: localhost
  app_port: "3000"
  app_db: app
  app_dbport: "5432"
  app_dbschema: app

secret:
  type: Opaque
  username: app_user
  password: app_user@pswd

podLabel:
  app: webapp
  service: api

psql:
  version: "13.1.5"
  repository: https://charts.bitnami.com/bitnami
  enabled: true
  image: postgres
  tag: 14-alpine

selectorLabel:
  app: webapp
  service: api

livenessConfig:
  initialDelaySeconds: 40
  periodSeconds: 10

readinessConfig:
  initialDelaySeconds: 40
  periodSeconds: 10

service:
  type: LoadBalancer
  port: 3000
  dbport: 5432

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

global:
  postgresql:
    auth:
      postgresPassword: root
      username: app_user
      password: app_user@pswd
      database: app
