---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  {{- template "webapp-helm-chart.labels" .}}
data:
  {{- template "webapp-helm-chart.configMap" .}}

