---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels: {{include "webapp-helm-chart.labels" . | indent 4 }}
data:
  {{- template "webapp-helm-chart.configData" .}}
