apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels: {{ include "webapp-helm-chart.db.labels" . | indent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
        - podSelector:
            matchLabels: {{ include "webapp-helm-chart.labels" . | indent 14 }}
      ports:
        - protocol: TCP
          port: 5432
