---
apiVersion: v1
kind: Service
metadata:
  name: psql-service
  namespace: {{ .Values.namespace }}
  {{- template "webapp-helm-chart.labels" .}}
spec:
  type: LoadBalancer
  selector:
    app: webapp
    service: api
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.dbport }}
      targetPort: {{ .Values.service.dbport }}
