apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-robocop
  namespace: {{ .Values.namespace }}
  labels: {{include "webapp-helm-chart.labels" . | indent 4 }}
type: {{ .Values.imagePullSecrets.type }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerConfig }}
