---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
  {{- template "webapp-helm-chart.labels" .}}
type: Opaque
data:
  # base64 encoded values
  flyway_user: YXBwX3VzZXI=
  flyway_password: YXBwX3VzZXJAcHN3ZA==
