---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
  labels: {{include "webapp-helm-chart.labels" . | indent 4 }}
type: {{ .Values.service.type }}
data:
  {{- template "webapp-helm-chart.secretData" .}}
