---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: webapp
  labels:
    app: webapp
    service: api
spec:
  type: {{.Values.service.type}}
  selector:
    app: webapp
    service: api
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: http
